### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by kequach** [Bastiaansen/MCLR-ECS-estimation#1]
Hello, I saw that this repository currently has no license attached. Did you maybe miss this or was this something you planned to add at a later stage (for example discussing appropriate license)? Technically, no one is allowed to reuse these resources if no license is given. If you need some help with this I'd be happy to assist. This is also the case for your other repo.

**Comment by Bastiaansen** [comment]
Thanks for letting me know. Licenses have been added!
